---
version: 1.0.5
slug: dinadns
name: DinaDNS
description: >-
  Free Dynamic DNS (DynDNS or DDNS) service with Let's Encrypt support
url: https://github.com/david1111967/hass/tree/main/dinadns
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
map:
  - ssl:rw
options:
  domains:
    - null
  token: null
  user: null
  aliases: []
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
schema:
  domains:
    - match(.+\.dinadns\.es)
  token: str
  user: str
  aliases:
    - alias: str
      domain: str
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
  seconds: int
  ipv4: str?
startup: services
